#!/usr/bin/env bash

killall dunst

i3-msg restart

notify-send -i display "Display profile" "$AUTORANDR_CURRENT_PROFILE"

nitrogen --restore
sleep 2
pidof picom > /dev/null || picom --experimental-backends &

