#!/usr/bin/env bash

nitrogen --restore

killall dunst

i3-msg restart

pidof picom > /dev/null || picom --experimental-backends &

notify-send -i display "Display profile" "$AUTORANDR_CURRENT_PROFILE"

